service:
  name: serverless-job-manager

frameworkVersion: '>=1.3.8 <2.0.0'

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'stage'}
  profile: ${opt:profile, 'gasbuddy-staging'}
  region: us-east-1
  environment:
    # NOTE: this is useful for local invocations and has no affect in deployed environments
    AWS_PROFILE: ${self:provider.profile}
    SERVICE_NAME: ${self:service.name}-${self:provider.stage}
    STATE_MACHINE_ARN_EXECUTE_JOB: ${self:resources.Outputs.ExecuteJobExecutionStateMachineARN.Value}
    STATE_MACHINE_ARN_QUEUE_JOB_EXECUTION: ${self:resources.Outputs.QueueJobExecutionStateMachineARN.Value}
    CLOUDWATCH_EVENTS_RULE_PREFIX: sjm.
    DYNAMODB_TABLE_NAME_JOBS: ${self:custom.dynamodb_table_name_jobs}
    DYNAMODB_INDEX_NAME_JOBS_GUID: ${self:custom.dynamodb_index_name_jobs_guid}
    # DYNAMODB_INDEX_NAME_JOBS_SCHEDULE: ${self:custom.dynamodb_index_name_jobs_schedule}
    DYNAMODB_TABLE_NAME_JOB_EXECUTIONS: ${self:custom.dynamodb_table_name_job_executions}
    DYNAMODB_PARTITION_COUNT_JOB_EXECUTIONS: 8
    # IAM_ROLE_ARN_STATE_MACHINE_EXECUTION:
    #   Fn::GetAtt: [ IamRoleStateMachineExecution, Arn ]
  iamRoleStatements:
    - Effect: Allow
      Action:
        - states:StartExecution
      Resource:
        - Ref: ExecuteJobExecution
    - Effect: Allow
      Action:
        - states:sendTaskSuccess
      Resource:
        - arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:activity:${self:custom.step_function_activity_name_await_callback}
    - Effect: Allow
      Action:
        - states:GetActivityTask
      Resource:
        - arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:activity:${self:custom.step_function_activity_name_await_callback}
    - Effect: Allow
      Action: iam:PassRole
      Resource:
        -  arn:aws:iam::#{AWS::AccountId}:role/${self:custom.iam_role_name_cloudwatch_events}
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - Fn::GetAtt: [ JobsDynamoDbTable, Arn ]
        - Fn::GetAtt: [ JobExecutionsDynamoDbTable, Arn ]
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
      Resource:
        - arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:${self:custom.sqs_fifo_queue_name_job_execution_events}
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource:
        - Fn::Join:
            - ""
            - - Fn::GetAtt: [ JobsDynamoDbTable, Arn ]
              - "/index/${self:custom.dynamodb_index_name_jobs_guid}"
    - Effect: Allow
      Action:
        - events:RemoveTargets
        - events:PutTargets
        - events:PutRule
        - events:DeleteRule
        - events:DescribeRule
        - events:ListRules
      Resource:
        # use tag-based permissions?... something more secure than a string prefix?
        - arn:aws:events:#{AWS::Region}:#{AWS::AccountId}:rule/${self:provider.environment.CLOUDWATCH_EVENTS_RULE_PREFIX}*
    - Effect: Allow
      Action:
        - events:ListRules
      Resource:
        # use tag-based permissions?... something more secure than a string prefix?
        - arn:aws:events:#{AWS::Region}:#{AWS::AccountId}:rule/*
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - ${self:custom.arn_prefix_lambda_function}-startExecutionWithEvent
        - ${self:custom.arn_prefix_lambda_function}-pollActivityTaskTokens

plugins:
  # - serverless-iam-roles-per-function
  - serverless-pseudo-parameters
  - serverless-step-functions
  - serverless-webpack

custom:
  version: 2
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packager: npm
  arn_prefix_lambda_function: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service.name}-${self:provider.stage}
  # serverless-iam-roles-per-function:
  #   defaultInherit: true
  dynamodb_table_name_jobs: ${self:service.name}-${self:provider.stage}-jobs
  dynamodb_table_name_job_executions: ${self:service.name}-${self:provider.stage}-job-executions
  dynamodb_index_name_jobs_guid: ${self:service.name}-${self:provider.stage}-jobs-guid
  # dynamodb_index_name_jobs_schedule: ${self:service.name}-${self:provider.stage}-jobs-schedule
  sqs_fifo_queue_name_job_execution_events: ${self:service.name}-${self:provider.stage}-job-execution-events.fifo
  iam_role_name_cloudwatch_events: ${self:service.name}-${self:provider.stage}-cloudwatchevents
  step_function_activity_name_await_callback: ${self:service.name}-${self:provider.stage}-awaitCallback
functions:
  # Step function task handlers
  workExecutionQueue:
    handler: handlers/work-execution-queue.handler
    description: Lambda that pulls a single execution event off the FIFO queue and starts a job execution
    timeout: 30
    environment:
      SQS_QUEUE_URL_JOB_EXECUTION_EVENTS:
        Ref: JobExecutionEventsFifoSqsQueue
      LAMBDA_ARN_START_EXECUTION_WITH_EVENT: ${self:resources.Outputs.StartExecutionWithEventLambdaFunctionARN.Value}
  startExecutionWithEvent:
    handler: handlers/start-execution-with-event.handler
    description: Lambda that receives the execution event starts the state machine execution.
  getJobByGuid:
    handler: handlers/get-job-by-guid.handler
  getJobLock:
    description: For exclusive jobs, locks the job record and passes job attributes to next task
    handler: handlers/get-job-lock.handler
  getJob:
    description: For non-exclusive jobs, passes job attributes to next task
    handler: handlers/get-job.handler
  getJobExecutionByExecutionKey:
    handler: handlers/get-job-execution-by-execution-key.handler
  insertJobExecution:
    handler: handlers/insert-job-execution.handler
    description: Lambda that inserts the pending job execution into DynamoDB
  invokeServiceExecution:
    handler: handlers/invoke-service-execution.handler
    description: Lambda that calls the invocation_target with the event details
    environment:
      API_BASE:
        Fn::Join:
          - ""
          - - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"
  # pollActivityTaskTokens:
  #   handler: handlers/poll-activity-task-tokens.handler
  #   description: Lambda that polls StepFunctions for the AwaitCallback activity task token and writes them to DynamoDb
  #   reservedConcurrency: 10
  #   timeout: 85 # TODO: tune this
  #   environment:
  #     POLL_TIMEOUT_SECONDS: 65
  #     STEP_FUNCTION_ACTIVITY_ARN_AWAIT_CALLBACK: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:activity:${self:custom.step_function_activity_name_await_callback}
  # launchActivityWorker:
  #   handler: handlers/launch-activity-worker.handler
  #   description: Lambda that launches the activity woker asynchronously
  #   environment:
  #     LAMBDA_ARN_POLL_ACTIVITY_TASK_TOKENS: ${self:resources.Outputs.PollActivityTaskTokensLambdaFunctionARN.Value}
  getActivityTaskToken:
    handler: handlers/get-activity-task-token.handler
    description: Attempts to retrieve the activity task token
    timeout: 90 # TODO: tune this
    environment:
      STEP_FUNCTION_ACTIVITY_ARN_AWAIT_CALLBACK: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:activity:${self:custom.step_function_activity_name_await_callback}
  insertActivityTaskToken:
    handler: handlers/insert-activity-task-token.handler
    timeout: 30 # allow time for retries

  # DynamoDB Stream handlers
  updateJobSchedule:
    handler: handlers/update-job-schedule.handler
    description: Lambda that receives the DynamoDb event when a job is updated, updates event rule
    environment:
      IAM_ROLE_ARN_CLOUDWATCH_EVENTS:
        Fn::GetAtt: [ IamRoleCloudWatchEvents, Arn ]
      SQS_QUEUE_ARN_JOB_EXECUTION_EVENTS:
        Fn::GetAtt: [ JobExecutionEventsFifoSqsQueue, Arn ]
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [ JobsDynamoDbTable, StreamArn ]
          batchSize: 1

  # API handlers
  putJob:
    handler: handlers/api/put-job.handler
    description: Idempotent job create/update
    events:
      - http:
          path: services/{serviceName}/jobs/{jobName}
          method: put
  deleteJob:
    handler: handlers/api/delete-job.handler
    description: Idempotent job delete
    events:
      - http:
          path: services/{serviceName}/jobs/{jobName}
          method: delete
  updateExecutionStatus:
    handler: handlers/api/update-execution-status.handler
    description: Endpoint for services to call with job results
  mockHttpInvokeTarget:
    handler: handlers/api/mock-http-invoke-target.handler
    description: Endpoint for testing HTTP invoke target
    events:
      - http:
          path: http-invoke
          method: post

stepFunctions:
  stateMachines:
    # putJobApiHandlerStepFunction:
    #   name: putJobApiHandler
    #   events:
    #     - http:
    #         path: services/{service_name}/jobs/{job_name}
    #         method: put
    #   definition:
    #     Comment:  Idempotent job create/update
    #     StartAt:
    #     PutJob:
    #       Type: Task
    #       Resource: ${self:custom.arn_prefix_lambda_function}-putJob
    #       End: true

    queueJobExecutionStepFunction:
      name: queueJobExecution
      definition:
        Comment: "Queue a job execution for the given CloudWatch Event Rule event"
        StartAt: AddToQueue
        States:
          AddToQueue:
            Type: Task
            Resource: arn:aws:states:::sqs:sendMessage
            Parameters:
              QueueUrl: https://sqs.#{AWS::Region}.amazonaws.com/#{AWS::AccountId}/${self:custom.sqs_fifo_queue_name_job_execution_events}
              MessageBody.$: "$"
              MessageGroupId.$: "$.sqsMessageGroupId"
              MessageDeduplicationId.$: "$.eventId"
            ResultPath: "$.sqs"
            Next: WorkExecutionQueue
          WorkExecutionQueue:
            Type: Task
            Resource: ${self:custom.arn_prefix_lambda_function}-workExecutionQueue
            End: true
            # lambda that pulls the next job off the queue and inserts it into dynamodb
          #   Type: Choice
          #   Choices:
          #     - Variable: "$.exclusive"
          #       BooleanEquals: true
          #       Next: WorkExecutionQueue
          #     - Variable: "$.exclusive"
          #       BooleanEquals: false
          #       Next: WorkParallelExecutionQueue
          # WorkExclusiveExecutionQueue:
          #   Type: Task
          #   Resource: ${self:custom.arn_prefix_lambda_function}-workExclusiveExecutionQueue
          #   End: true
          # WorkParallelExecutionQueue:
          #   Type: Task
          #   Resource: ${self:custom.arn_prefix_lambda_function}-workParallelExecutionQueue
          #   End: true

    executeJobExecutionStepFunction:
      name: executeJobExecution
      definition:
        Comment: "Executes a job for the given CloudWatch Event Rule event"
        StartAt: GetLockIfExclusive
        States:
          GetLockIfExclusive:
            Type: Choice
            Choices:
              - Variable: "$.exclusive"
                BooleanEquals: true
                Next: GetJobLock
              - Variable: "$.exclusive"
                BooleanEquals: false
                Next: GetJob
          GetJobLock:
            Type: Task
            Resource: ${self:custom.arn_prefix_lambda_function}-getJobLock
            Next: InsertJobExecution
          GetJob:
            Type: Task
            Resource: ${self:custom.arn_prefix_lambda_function}-getJob
            Next: InsertJobExecution
          InsertJobExecution:
            Type: Task
            Resource: ${self:custom.arn_prefix_lambda_function}-insertJobExecution
            Next: Callback
          # LaunchActivityWorker:
          #   Type: Task
          #   Resource: ${self:custom.arn_prefix_lambda_function}-launchActivityWorker
          #   Next: Callback
          Callback:
            Type: Parallel
            Next: FinishCallback
            Branches:
              - StartAt: AwaitCallback
                States:
                  AwaitCallback:
                    Type: Task
                    Resource: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:activity:${self:custom.step_function_activity_name_await_callback}
                    HeartbeatSeconds: 60
                    End: true
              - StartAt: DelayForActivityStart
                States:
                  DelayForActivityStart:
                    Type: Wait
                    Seconds: 3
                    Next: GetActivityTaskToken
                  # LaunchActivityWorker:
                  #   Type: Task
                  #   Resource: ${self:custom.arn_prefix_lambda_function}-launchActivityWorker
                  #   Next: InvokeServiceExecution
                  GetActivityTaskToken:
                    Type: Task
                    Resource: ${self:custom.arn_prefix_lambda_function}-getActivityTaskToken
                    Next: InsertActivityTaskToken
                  InsertActivityTaskToken:
                    Type: Task
                    Resource: ${self:custom.arn_prefix_lambda_function}-insertActivityTaskToken
                    Next: LoopGetActivityTaskToken
                  LoopGetActivityTaskToken:
                    Type: Choice
                    Choices:
                      - Variable: "$.loop"
                        BooleanEquals: true
                        Next: GetActivityTaskToken
                      - Variable: "$.loop"
                        BooleanEquals: false
                        Next: InvokeServiceExecution
                  InvokeServiceExecution:
                    Type: Task
                    Resource: ${self:custom.arn_prefix_lambda_function}-invokeServiceExecution
                    InputPath: "$.jobExecution"
                    End: true
          FinishCallback:
            # Type: Task
            # Resource: ${self:custom.arn_prefix_lambda_function}-finishCallback
            Type: Pass
            End: true
    executionCallbackStepFunction:
      name: executionCallback
      events:
        - http:
            path: callback/{jobGuid}/{encodedExecutionKey}
            method: post
            request:
              template:
                application/json: |
                  #set( $body = $util.escapeJavaScript($input.json('$')) )
                  {
                    "stateMachineArn":"arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:executionCallback",
                    "input" : "{\"pathParameters\": { \"jobGuid\": \"$input.params('jobGuid')\", \"encodedExecutionKey\": \"$input.params('encodedExecutionKey')\" }}"
                  }
      definition:
        Comment: Processes the results of a service's job execution
        StartAt: GetJobAndExecution
        States:
          GetJobAndExecution:
            Type: Parallel
            Next: UpdateExecutionStatus
            Branches:
              - StartAt: GetJobByGuid
                States:
                  GetJobByGuid:
                    Type: Task
                    Resource: ${self:custom.arn_prefix_lambda_function}-getJobByGuid
                    End: true
              - StartAt: GetJobExecutionByExecutionKey
                States:
                  GetJobExecutionByExecutionKey:
                    Type: Task
                    Resource: ${self:custom.arn_prefix_lambda_function}-getJobExecutionByExecutionKey
                    End: true
          UpdateExecutionStatus:
            Type: Task
            Resource: ${self:custom.arn_prefix_lambda_function}-updateExecutionStatus
            End: true

  activities:
    - ${self:custom.step_function_activity_name_await_callback}

resources:
  Outputs:
    ExecuteJobExecutionStateMachineARN:
      Description: The ARN of the ExecuteJobExecution state machine
      Value:
        Ref: ExecuteJobExecution
    QueueJobExecutionStateMachineARN:
      Description: The ARN of the QueueJobExecution state machine
      Value:
        Ref: QueueJobExecution
    StartExecutionWithEventLambdaFunctionARN:
      Value:
        Fn::GetAtt: [ StartExecutionWithEventLambdaFunction, Arn ]
    # PollActivityTaskTokensLambdaFunctionARN:
    #   Value:
    #     Fn::GetAtt: [ PollActivityTaskTokensLambdaFunction, Arn ]
  Resources:
    JobExecutionEventsFifoSqsQueue:
      Type: AWS::SQS::Queue # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html
      Properties:
        QueueName: ${self:custom.sqs_fifo_queue_name_job_execution_events}
        ContentBasedDeduplication: true
        FifoQueue: true
        # MessageRetentionPeriod: 82800 # 23 hours
    JobsDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamodb_table_name_jobs}
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: serviceName
            AttributeType: S
          - AttributeName: jobName
            AttributeType: S
          - AttributeName: guid
            AttributeType: S
        KeySchema:
          - AttributeName: serviceName
            KeyType: HASH
          - AttributeName: jobName
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: ${self:custom.dynamodb_index_name_jobs_guid}
            KeySchema:
              - AttributeName: guid
                KeyType: HASH
            Projection:
              ProjectionType: KEYS_ONLY
          # - IndexName: ${self:custom.dynamodb_index_name_jobs_schedule}
          #   KeySchema:
          #     - AttributeName: schedule
          #       KeyType: HASH
          #     - AttributeName: service_job
          #       KeyType: RANGE
          #   Projection:
          #     ProjectionType: KEYS_ONLY
    JobExecutionsDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamodb_table_name_job_executions}
        BillingMode: PAY_PER_REQUEST
        # StreamSpecification:
        #   StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: partitionKey
            AttributeType: S
          - AttributeName: sortKey
            AttributeType: S
        KeySchema:
          # `${DATE}.${parseInt(eventId.replace(/[^0-9a-fA-F]/g, '').substr(-13),16) % DYNAMODB_PARTITION_COUNT_JOB_EXECUTIONS}`
          # exmaple: 20190321.1
          - AttributeName: partitionKey
            KeyType: HASH
          # `${serviceName}:${jobName}:${eventTimeMs}:${eventId}`
          - AttributeName: sortKey
            KeyType: RANGE
    IamRoleCloudWatchEvents:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - events.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: root
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                # - Effect: Allow
                #   Action:
                #     - sqs:SendMessage
                #   Resource:
                #     - Fn::GetAtt: [ JobExecutionEventsFifoSqsQueue, Arn ]
                - Effect: Allow
                  Action:
                    - states:StartExecution
                  Resource:
                    # - Ref: ExecuteJobExecution
                    - Ref: QueueJobExecution
                # - Effect: Allow
                #   Action:
                #     - lambda:InvokeFunction
                #   Resource:
                #     - Fn::GetAtt: [ StartExecutionWithEventLambdaFunction, Arn ]
        RoleName: ${self:custom.iam_role_name_cloudwatch_events}
